mp.messaging.incoming.incomingmessages.group.id=notifications-connector-microsoft-teams
notifications.connector.name=teams
notifications.connector.supported-connector-headers=${notifications.connector.name}

quarkus.http.port=9002

# Configure the limit of how many messages the connector can process in parallel
smallrye.messaging.worker.connector-thread-pool.max-concurrency=20

quarkus.log.cloudwatch.enabled=false
quarkus.log.cloudwatch.level=INFO
quarkus.log.cloudwatch.log-stream-name=${HOST_NAME:notifications-connector-microsoft-teams}

quarkus.log.sentry.enabled=false
quarkus.log.sentry.in-app-packages=com.redhat.cloud.notifications

quarkus.kafka.devservices.port=9092

quarkus.unleash.active=false
quarkus.unleash.url=http://localhost:4242
