mp.messaging.incoming.incomingmessages.group.id=notifications-connector-slack
notifications.connector.name=slack
notifications.connector.supported-connector-headers=${notifications.connector.name}

quarkus.http.port=9004

# Configure the limit of how many messages the connector can process in parallel
smallrye.messaging.worker.connector-thread-pool.max-concurrency=20

quarkus.log.cloudwatch.enabled=false
quarkus.log.cloudwatch.level=INFO
quarkus.log.cloudwatch.log-stream-name=${HOST_NAME:notifications-connector-slack}

quarkus.log.sentry.enabled=false
quarkus.log.sentry.in-app-packages=com.redhat.cloud.notifications

quarkus.kafka.devservices.port=9092

%test.quarkus.log.category."com.redhat.cloud.notifications".level=DEBUG

quarkus.unleash.active=false
quarkus.unleash.url=http://localhost:4242
