{
 "title": "Notifications Dashboard",
 "tags": [ "notifications" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "environment",
    "query": "insights-perf-prometheus, crcs02ue1-prometheus, crcp01ue1-prometheus, hccs01ue1-prometheus, hccp01ue1-prometheus"
   },
   {
    "name": "rds_datasource",
    "label": "RDS",
    "query": "AWS insights-prod , AWS insights-stage"
   },
   { "name": "aws_resources_exporter", "label": "Resources Exporter", "query": "prometheus" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": {}
   },
   {
    "name": "msk_cluster",
    "label": "MSK Cluster",
    "query": {
     "query": "label_values(aws_kafka_sum_offset_lag_sum,cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Level Indicators (SLI)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate uptime [30d]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"notifications\"}[30d])",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  },
  {
   "title": "Latency uptime [30d]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"notifications\"}[30d])",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  },
  { "title": "Pods health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "notifications-backend-service - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-backend-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "notifications-engine-service - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-engine-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "notifications-gw-service - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-gw-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Google Chat - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-google-chat-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Microsoft Teams - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-microsoft-teams-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "PagerDuty - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-pagerduty-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "ServiceNow - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-servicenow-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Slack - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-slack-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "notifications-backend-service - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-backend-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "notifications-engine-service - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-engine-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "notifications-gw-service - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-gw-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Google Chat - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-google-chat-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Microsoft Teams - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-microsoft-teams-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "PagerDuty - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-pagerduty-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "ServiceNow - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-servicenow-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Slack - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-slack-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "notifications-backend-service - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-backend-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-engine-service - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-engine-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-gw-service - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-gw-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Google Chat - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-google-chat-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Microsoft Teams - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-microsoft-teams-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PagerDuty - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-pagerduty-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ServiceNow - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-servicenow-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slack - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-slack-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-backend-service - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-backend-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-engine-service - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-engine-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-gw-service - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-gw-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Google Chat - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-google-chat-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Microsoft Teams - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-microsoft-teams-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PagerDuty - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-pagerduty-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ServiceNow - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-servicenow-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slack - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-slack-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Splunk - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-splunk-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Webhook - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-webhook-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Email - UPs",
   "type": "stat",
   "description": "Number of running pods in the environment",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-email-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Drawer - UPs",
   "type": "stat",
   "description": "Number of running pods in the environment",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-connector-drawer-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Recipients-resolver - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-recipients-resolver-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Splunk - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-splunk-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Webhook - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-webhook-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Email - Restarts",
   "type": "stat",
   "description": "Number of pod restarts since the last deployment",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-email-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Drawer - Restarts",
   "type": "stat",
   "description": "Number of pod restarts since the last deployment",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-connector-drawer-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Recipients-resolver - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-recipients-resolver-service\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Splunk - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-splunk-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Webhook - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-webhook-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Email - Memory leak detection",
   "type": "timeseries",
   "description": "Graph that helps identifying if any memory leaks have occurred.",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-connector-email-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Drawer - Container memory usage",
   "type": "timeseries",
   "description": "Graph that helps identifying if any memory leaks have occurred.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"notifications-connector-drawer-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Recipients-resolver - Memory leak detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"notifications-recipients-resolver-service\", area=\"heap\", id=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Splunk - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-splunk-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Webhook - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-webhook-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Email - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-email-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Drawer - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-connector-drawer-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Recipients-resolver - Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=\"notifications-recipients-resolver-service\", mode!=\"idle\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Production database's health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The freeable memory is the amount of memory available in the RDS instance. A low freeable memory value and a high swap value might signal that the instance needs to be upgraded.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "description": "Shows the databases read operations, the write operations, and the burst balance we currently have available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "timeseries",
   "description": "Shows the current free available storage space for the database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Shows the current throughput of the database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "Shows the number of active database connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Shows the latency of the read and write operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Kafka issues indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Kafka Lag (messages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{cluster_name=\"$msk_cluster\", topic=~\".*platform.notifications.ingress\"})",
     "legendFormat": "{topic=\"{{topic}}\", consumer_group=\"{{consumer_group}}\"}"
    },
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{cluster_name=\"$msk_cluster\", topic=~\".*platform.notifications.tocamel\", consumer_group=~\"notifications-connector-.+\"})",
     "legendFormat": "{topic=\"{{topic}}\", consumer_group=\"{{consumer_group}}\"}"
    },
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{cluster_name=\"$msk_cluster\", topic=~\".*platform.notifications.fromcamel\"})",
     "legendFormat": "{topic=\"{{topic}}\", consumer_group=\"{{consumer_group}}\"}"
    },
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{cluster_name=\"$msk_cluster\", topic=~\".*platform.notifications.aggregation\"})",
     "legendFormat": "{topic=\"{{topic}}\", consumer_group=\"{{consumer_group}}\"}"
    },
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{cluster_name=\"$msk_cluster\", topic=~\".*platform.notifications.connector.email.high.volume\"})",
     "legendFormat": "{topic=\"{{topic}}\", consumer_group=\"{{consumer_group}}\"}"
    }
   ]
  },
  {
   "title": "Events consumed per bundle/app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bundle, application) (increase(input_consumed_seconds_count{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "{{bundle}}/{{application}}"
    }
   ]
  },
  {
   "title": "Events processed, rejected or that caused an exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(processor_input_processed_total{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(increase(input_rejected_total{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "rejected"
    },
    {
     "expr": "sum(increase(input_processing_exception_total{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "exception"
    }
   ]
  },
  {
   "title": "Connectors payload size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (connector, event_type) (notifications_tocamel_payload_content_size_bytes_max)",
     "legendFormat": "{{connector}}/{{event_type}}"
    }
   ]
  },
  { "title": "Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Aggregator cronjob - duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(aggregator_job_duration_seconds[5m])",
     "legendFormat": "aggregator cron job"
    }
   ]
  },
  {
   "title": "Aggregation consumed time - in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "targets": [
    {
     "expr": "max_over_time(aggregation_time_consumed_seconds_max[10m])",
     "legendFormat": "{{bundle}}/{{application}}"
    }
   ]
  },
  {
   "title": "Aggregator cronjob - last successful run",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregator_job_last_success * 1000"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Email connector",
   "type": "timeseries",
   "description": "Gives information regarding the rate of successes, failures and retries for the email connector.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-email-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-email-service\", routeId=\"email_subscription\"}[5m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(camel_email_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "Webhook",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 106 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-webhook-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success (old)"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-webhook-service\", routeId=\"webhook\"}[5m]))",
     "legendFormat": "Failure (old)"
    },
    {
     "expr": "sum(increase(camel_webhook_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_succeeded_total{connector=\"webhook\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_failed_total{connector=\"webhook\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Microsoft Teams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-microsoft-teams-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success (old)"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-microsoft-teams-service\", routeId=\"teams\"}[5m]))",
     "legendFormat": "Failure (old)"
    },
    {
     "expr": "sum(increase(camel_teams_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_succeeded_total{connector=\"teams\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_failed_total{connector=\"teams\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "PagerDuty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 106 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-pagerduty-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-pagerduty-service\", routeId=\"teams\"}[5m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(camel_pagerduty_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "Slack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-slack-service\", routeId=\"slack\"}[5m]))",
     "legendFormat": "Success (old)"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-slack-service\", routeId=\"slack\"}[5m]))",
     "legendFormat": "Failure (old)"
    },
    {
     "expr": "sum(increase(camel_slack_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_succeeded_total{connector=\"slack\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_failed_total{connector=\"slack\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Splunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-splunk-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-splunk-service\", routeId=\"splunk\"}[5m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(camel_splunk_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "Google Chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-google-chat-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success (old)"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-google-chat-service\", routeId=\"google_chat\"}[5m]))",
     "legendFormat": "Failure (old)"
    },
    {
     "expr": "sum(increase(camel_google_chat_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_succeeded_total{connector=\"google_chat\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_failed_total{connector=\"google_chat\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "ServiceNow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_succeeded_total{service=\"notifications-connector-servicenow-service\", routeId=\"success\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(camel_exchanges_failures_handled_total{service=\"notifications-connector-servicenow-service\", routeId=\"servicenow\"}[5m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(camel_servicenow_retry_counter_total[5m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "Drawer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "sum(increase(notifications_connector_messages_succeeded_total{connector=\"drawer\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(notifications_connector_messages_failed_total{connector=\"drawer\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "notifications-backend-service - HTTP requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{container=\"notifications-backend-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notifications-engine-service - HTTP requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{container=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notifications-gw-service - HTTP requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{container=\"notifications-gw-service\", uri!~\"/health/live|/health/ready|/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/integrations.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/integrations.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/user-config.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/user-config.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/facets.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/facets.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/events.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/events.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/eventTypes.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/eventTypes.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/behaviorGroups.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/behaviorGroups.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/bundles.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/bundles.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/drawer*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/drawer*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "External dependencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Recipients resolver - Average response time spent by external requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(user_provider_get_users_total_seconds_sum{service=\"notifications-recipients-resolver-service\"}[5m])) / sum(rate(user_provider_get_users_total_seconds_count{service=\"notifications-recipients-resolver-service\"}[5m]))",
     "legendFormat": "avg response time"
    }
   ]
  },
  {
   "title": "Recipients resolver — Successful requests",
   "type": "timeseries",
   "description": "Shows the increase of the successful requests made to the external services the application depends on.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user_provider) (increase(notifications_recipients_resolver_requests_total{result=\"successes\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exports service",
   "type": "timeseries",
   "description": "Information about the health of the integration.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "sum(rate(exports_service_successes_total[5m]))",
     "legendFormat": "Successful exports"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"client.error\"}[5m]))",
     "legendFormat": "Client error responses from the exports service"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"empty.body\"}[5m]))",
     "legendFormat": "Empty body received in Cloud Event failure"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"non.parseable.cloud.event\"}[5m]))",
     "legendFormat": "Non parseable Cloud Event received"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"server.error\"}[5m]))",
     "legendFormat": "Internal server error responses from the exports service"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"unable.extract.filters\"}[5m]))",
     "legendFormat": "Unable to extract the export filters from the request"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"unable.transform.data\"}[5m]))",
     "legendFormat": "Unable to transform the data in the requested format"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"unsupported.format\"}[5m]))",
     "legendFormat": "Unsupported export format requested"
    },
    {
     "expr": "sum(rate(exports_service_failures_total{error=\"unsupported.resource.type\"}[5m]))",
     "legendFormat": "Unsupported resource type requested"
    }
   ]
  },
  {
   "title": "Recipients resolver — Failed requests",
   "type": "timeseries",
   "description": "Shows the increase of the failed requests made to the external services the application depends on.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user_provider) (increase(notifications_recipients_resolver_requests_total{result=\"failures\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time spent calling customers endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(webhook_endpoint_response_time_seconds_sum{service=\"notifications-connector-webhook-service\"}[5m])) / sum(increase(webhook_endpoint_response_time_seconds_count{service=\"notifications-connector-webhook-service\"}[5m]))",
     "legendFormat": "connector webhook (old)"
    },
    {
     "expr": "sum(increase(email_bop_response_time_seconds_sum{service=\"notifications-connector-email-service\"}[5m])) / sum(increase(email_bop_response_time_seconds_count{service=\"notifications-connector-email-service\"}[5m]))",
     "legendFormat": "connector email BOP"
    },
    {
     "expr": "sum(increase(googlechat_response_time_seconds_sum{service=\"notifications-connector-google-chat-service\"}[5m])) / sum(increase(googlechat_response_time_seconds_count{service=\"notifications-connector-google-chat-service\"}[5m]))",
     "legendFormat": "connector Google Chat (old)"
    },
    {
     "expr": "sum(increase(splunk_response_time_seconds_sum{service=\"notifications-connector-splunk-service\"}[5m])) / sum(increase(splunk_response_time_seconds_count{service=\"notifications-connector-splunk-service\"}[5m]))",
     "legendFormat": "connector Splunk"
    },
    {
     "expr": "sum(increase(servicenow_response_time_seconds_sum{service=\"notifications-connector-servicenow-service\"}[5m])) / sum(increase(servicenow_response_time_seconds_count{service=\"notifications-connector-servicenow-service\"}[5m]))",
     "legendFormat": "connector ServiceNow"
    },
    {
     "expr": "sum(increase(teams_response_time_seconds_sum{service=\"notifications-connector-microsoft-teams-service\"}[5m])) / sum(increase(teams_response_time_seconds_count{service=\"notifications-connector-microsoft-teams-service\"}[5m]))",
     "legendFormat": "connector Ms Teams"
    },
    {
     "expr": "sum(increase(pagerduty_response_time_seconds_sum{service=\"notifications-connector-pagerduty-service\"}[5m])) / sum(increase(pagerduty_response_time_seconds_count{service=\"notifications-connector-pagerduty-service\"}[5m]))",
     "legendFormat": "connector Slack"
    },
    {
     "expr": "sum(increase(notifications_connector_handler_duration_seconds_sum{connector=\"google_chat\"}[5m])) / sum(increase(notifications_connector_handler_duration_seconds_count{connector=\"google_chat\"}[5m]))",
     "legendFormat": "connector Google Chat"
    },
    {
     "expr": "sum(increase(notifications_connector_handler_duration_seconds_sum{connector=\"webhook\"}[5m])) / sum(increase(notifications_connector_handler_duration_seconds_count{connector=\"webhook\"}[5m]))",
     "legendFormat": "connector webhook"
    },
    {
     "expr": "sum(increase(notifications_connector_handler_duration_seconds_sum{connector=\"drawer\"}[5m])) / sum(increase(notifications_connector_handler_duration_seconds_count{connector=\"drawer\"}[5m]))",
     "legendFormat": "connector drawer"
    }
   ]
  },
  {
   "title": "Sources — Maximum time spent fetching secrets",
   "type": "timeseries",
   "description": "Shows the maximum time the different services spent fetching the secrets from Sources",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(service) (sources_get_secret_request_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sources — Number of secrets fetched",
   "type": "timeseries",
   "description": "Shows the number of secrets fetched by the different services.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service) (increase(sources_get_secret_request_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kessel",
   "type": "timeseries",
   "description": "Shows the increase of the successful requests made to the external services the application depends on.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(notifications_kessel_inventory_integration_count_total{result=\"successes\"}[$__rate_interval]))",
     "legendFormat": "Inventory successes"
    },
    {
     "expr": "sum (increase(notifications_kessel_inventory_integration_count_total{result=\"failures\"}[$__rate_interval]))",
     "legendFormat": "Inventory failures"
    },
    {
     "expr": "sum (increase(notifications_kessel_relationships_permission_check_count_total{result=\"successes\"}[$__rate_interval])) + sum (increase(notifications_kessel_relationships_lookup_check_count_total{result=\"successes\"}[$__rate_interval]))",
     "legendFormat": "Relationships successes"
    },
    {
     "expr": "sum (increase(notifications_kessel_relationships_permission_check_count_total{result=\"failures\"}[$__rate_interval])) + sum (increase(notifications_kessel_relationships_lookup_check_count_total{result=\"failures\"}[$__rate_interval]))",
     "legendFormat": "Relationships failures"
    }
   ]
  },
  { "title": "3Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "API error rate",
   "type": "timeseries",
   "description": "Proportion of 5xx status codes returned from this service.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"notifications\",status=\"5xx\"}[5m])) / sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 181 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"notifications\"}[5m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}